export const timezones = [
  // Pacific
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "Pacific/Marquesas", label: "(GMT-09:30) Marquesas Islands" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  { value: "America/Los_Angeles", label: "(GMT-08:00) Pacific Time (US & Canada)" },
  { value: "America/Tijuana", label: "(GMT-08:00) Tijuana, Baja California" },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Phoenix", label: "(GMT-07:00) Arizona" },
  { value: "America/Chihuahua", label: "(GMT-07:00) Chihuahua, La Paz, Mazatlan" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  { value: "America/Mexico_City", label: "(GMT-06:00) Mexico City" },
  { value: "America/Guatemala", label: "(GMT-06:00) Central America" },
  { value: "America/New_York", label: "(GMT-05:00) Eastern Time (US & Canada)" },
  { value: "America/Bogota", label: "(GMT-05:00) Bogota, Lima, Quito" },
  { value: "America/Caracas", label: "(GMT-04:00) Caracas" },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  { value: "America/La_Paz", label: "(GMT-04:00) La Paz" },
  { value: "America/Santiago", label: "(GMT-04:00) Santiago" },
  { value: "America/St_Johns", label: "(GMT-03:30) Newfoundland" },
  { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
  { value: "America/Argentina/Buenos_Aires", label: "(GMT-03:00) Buenos Aires" },
  { value: "America/Godthab", label: "(GMT-03:00) Greenland" },
  { value: "America/Montevideo", label: "(GMT-03:00) Montevideo" },
  { value: "America/Noronha", label: "(GMT-02:00) Mid-Atlantic" },
  { value: "Atlantic/Cape_Verde", label: "(GMT-01:00) Cape Verde Is." },
  { value: "Atlantic/Azores", label: "(GMT-01:00) Azores" },

  // Europe & Africa
  { value: "Europe/London", label: "(GMT+00:00) London, Edinburgh, Dublin" },
  { value: "Europe/Lisbon", label: "(GMT+00:00) Lisbon" },
  { value: "Africa/Casablanca", label: "(GMT+00:00) Casablanca" },
  { value: "Africa/Monrovia", label: "(GMT+00:00) Monrovia, Reykjavik" },
  { value: "Europe/Berlin", label: "(GMT+01:00) Berlin, Stockholm, Rome, Bern" },
  { value: "Europe/Paris", label: "(GMT+01:00) Paris, Madrid, Brussels" },
  { value: "Europe/Amsterdam", label: "(GMT+01:00) Amsterdam, Copenhagen" },
  { value: "Europe/Prague", label: "(GMT+01:00) Prague, Budapest, Warsaw" },
  { value: "Europe/Vienna", label: "(GMT+01:00) Vienna, Ljubljana, Bratislava" },
  { value: "Africa/Lagos", label: "(GMT+01:00) West Central Africa" },
  { value: "Europe/Athens", label: "(GMT+02:00) Athens, Bucharest" },
  { value: "Europe/Istanbul", label: "(GMT+03:00) Istanbul" },
  { value: "Europe/Helsinki", label: "(GMT+02:00) Helsinki, Kyiv, Riga" },
  { value: "Africa/Cairo", label: "(GMT+02:00) Cairo" },
  { value: "Africa/Harare", label: "(GMT+02:00) Harare, Pretoria" },
  { value: "Asia/Jerusalem", label: "(GMT+02:00) Jerusalem" },
  { value: "Europe/Moscow", label: "(GMT+03:00) Moscow, St. Petersburg" },
  { value: "Asia/Riyadh", label: "(GMT+03:00) Kuwait, Riyadh" },
  { value: "Africa/Nairobi", label: "(GMT+03:00) Nairobi" },
  { value: "Asia/Baghdad", label: "(GMT+03:00) Baghdad" },

  // Asia
  { value: "Asia/Tehran", label: "(GMT+03:30) Tehran" },
  { value: "Asia/Dubai", label: "(GMT+04:00) Abu Dhabi, Muscat" },
  { value: "Asia/Baku", label: "(GMT+04:00) Baku" },
  { value: "Asia/Yerevan", label: "(GMT+04:00) Yerevan" },
  { value: "Asia/Kabul", label: "(GMT+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(GMT+05:00) Karachi, Islamabad" },
  { value: "Asia/Tashkent", label: "(GMT+05:00) Tashkent" },
  { value: "Asia/Kolkata", label: "(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi" },
  { value: "Asia/Colombo", label: "(GMT+05:30) Sri Jayawardenepura" },
  { value: "Asia/Kathmandu", label: "(GMT+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(GMT+06:00) Dhaka" },
  { value: "Asia/Almaty", label: "(GMT+06:00) Almaty, Novosibirsk" },
  { value: "Asia/Yangon", label: "(GMT+06:30) Yangon (Rangoon)" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi, Jakarta" },
  { value: "Asia/Krasnoyarsk", label: "(GMT+07:00) Krasnoyarsk" },
  { value: "Asia/Shanghai", label: "(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi" },
  { value: "Asia/Singapore", label: "(GMT+08:00) Singapore" },
  { value: "Asia/Taipei", label: "(GMT+08:00) Taipei" },
  { value: "Asia/Manila", label: "(GMT+08:00) Manila" },
  { value: "Asia/Hong_Kong", label: "(GMT+08:00) Hong Kong" },
  { value: "Asia/Kuala_Lumpur", label: "(GMT+08:00) Kuala Lumpur" },
  { value: "Asia/Jakarta", label: "(GMT+07:00) Jakarta" },
  { value: "Australia/Perth", label: "(GMT+08:00) Perth" },
  { value: "Asia/Irkutsk", label: "(GMT+08:00) Irkutsk, Ulaan Bataar" },
  { value: "Asia/Seoul", label: "(GMT+09:00) Seoul" },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Osaka, Sapporo, Tokyo" },
  { value: "Asia/Yakutsk", label: "(GMT+09:00) Yakutsk" },
  { value: "Australia/Darwin", label: "(GMT+09:30) Darwin" },
  { value: "Australia/Adelaide", label: "(GMT+09:30) Adelaide" },
  { value: "Australia/Sydney", label: "(GMT+10:00) Canberra, Melbourne, Sydney" },
  { value: "Australia/Brisbane", label: "(GMT+10:00) Brisbane" },
  { value: "Australia/Hobart", label: "(GMT+10:00) Hobart" },
  { value: "Asia/Vladivostok", label: "(GMT+10:00) Vladivostok" },
  { value: "Pacific/Guam", label: "(GMT+10:00) Guam, Port Moresby" },
  { value: "Asia/Magadan", label: "(GMT+11:00) Magadan, Solomon Is." },
  { value: "Pacific/Norfolk", label: "(GMT+11:00) Norfolk Island" },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland, Wellington" },
  { value: "Pacific/Fiji", label: "(GMT+12:00) Fiji, Kamchatka, Marshall Is." },
  { value: "Pacific/Tongatapu", label: "(GMT+13:00) Nuku'alofa" },
  { value: "Pacific/Apia", label: "(GMT+13:00) Samoa" },
  { value: "Pacific/Kiritimati", label: "(GMT+14:00) Line Islands" },

  // Additional major cities
  { value: "America/Toronto", label: "(GMT-05:00) Toronto" },
  { value: "America/Vancouver", label: "(GMT-08:00) Vancouver" },
  { value: "Europe/Rome", label: "(GMT+01:00) Rome" },
  { value: "Europe/Madrid", label: "(GMT+01:00) Madrid" },
  { value: "Europe/Zurich", label: "(GMT+01:00) Zurich" },
  { value: "Asia/Ho_Chi_Minh", label: "(GMT+07:00) Ho Chi Minh City" },
  { value: "Asia/Phnom_Penh", label: "(GMT+07:00) Phnom Penh" },
  { value: "Asia/Vientiane", label: "(GMT+07:00) Vientiane" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Honolulu" },
]
