export const timezones = [
  { value: "Pacific/Midway", label: "(GMT-11:00) Midway Island, Samoa" },
  { value: "Pacific/Honolulu", label: "(GMT-10:00) Hawaii" },
  { value: "America/Anchorage", label: "(GMT-09:00) Alaska" },
  { value: "America/Los_Angeles", label: "(GMT-08:00) Pacific Time (US & Canada)" },
  { value: "America/Denver", label: "(GMT-07:00) Mountain Time (US & Canada)" },
  { value: "America/Chicago", label: "(GMT-06:00) Central Time (US & Canada)" },
  { value: "America/New_York", label: "(GMT-05:00) Eastern Time (US & Canada)" },
  { value: "America/Caracas", label: "(GMT-04:30) Caracas" },
  { value: "America/Halifax", label: "(GMT-04:00) Atlantic Time (Canada)" },
  { value: "America/Sao_Paulo", label: "(GMT-03:00) Brasilia" },
  { value: "Atlantic/Cape_Verde", label: "(GMT-01:00) Cape Verde Is." },
  { value: "Europe/London", label: "(GMT) Greenwich Mean Time : Dublin, Edinburgh, London" },
  { value: "Europe/Berlin", label: "(GMT+01:00) Berlin, Rome, Stockholm, Vienna" },
  { value: "Europe/Paris", label: "(GMT+01:00) Paris, Madrid" },
  { value: "Africa/Cairo", label: "(GMT+02:00) Cairo" },
  { value: "Europe/Athens", label: "(GMT+02:00) Athens, Istanbul" },
  { value: "Asia/Jerusalem", label: "(GMT+02:00) Jerusalem" },
  { value: "Asia/Riyadh", label: "(GMT+03:00) Riyadh, Kuwait" },
  { value: "Asia/Moscow", label: "(GMT+03:00) Moscow, St. Petersburg" },
  { value: "Asia/Dubai", label: "(GMT+04:00) Abu Dhabi, Dubai" },
  { value: "Asia/Kabul", label: "(GMT+04:30) Kabul" },
  { value: "Asia/Karachi", label: "(GMT+05:00) Karachi" },
  { value: "Asia/Kolkata", label: "(GMT+05:30) Kolkata, New Delhi" },
  { value: "Asia/Kathmandu", label: "(GMT+05:45) Kathmandu" },
  { value: "Asia/Dhaka", label: "(GMT+06:00) Dhaka" },
  { value: "Asia/Bangkok", label: "(GMT+07:00) Bangkok, Hanoi" },
  { value: "Asia/Singapore", label: "(GMT+08:00) Singapore, Hong Kong" },
  { value: "Asia/Tokyo", label: "(GMT+09:00) Tokyo" },
  { value: "Australia/Sydney", label: "(GMT+10:00) Sydney" },
  { value: "Pacific/Noumea", label: "(GMT+11:00) Noumea" },
  { value: "Pacific/Auckland", label: "(GMT+12:00) Auckland" },
  { value: "Pacific/Tongatapu", label: "(GMT+13:00) Nuku'alofa" },
]
